### ISSUE TITLE
Having issues with Ble

### ISSUE THREAD

**Issue by ssendhil12** [aschulz90/MagicMirrorApp#1]
Thanks for the great module. Whenever I add the Ble interface to the config.js I get the following error. in the logs of pm2..ANy help is appreciated.

Error: Module version mismatch. Expected 50, got 48.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/ble_app_interface/node_modules/bluetooth-hci-socket/lib/native.js:3:15)

**Comment by aschulz90** [comment]
Hi, sorry for the late answer!

The solution is described in the readme for ble_app_interface:

>If you get an errormessage similiar to this one: Module version mismatch. Expected 48, got 47., you need to rebuild bleno, because Electron is build against another Node version. To do this:

    cd into MagicMirror/modules/ble_app_interface/node_modules/bleno
    npm rebuild --runtime=electron --target=USED_ELECTRON_VERSION --disturl=https://atom.io/download/atom-shell --abi=XX

So in your case, it should be:

> npm rebuild --runtime=electron --target=1.4.7 --disturl=https://atom.io/download/atom-shell --abi=50
